const express = require('express');
const { registerUser, loginUser,getUserDetails, logout, updatePassword, updateProfile, getAllUser, getSingleUser, updateUserRole, deleteUser, } = require('../controllers/userControllers');
const router = express.Router();
const { isAuthenticatedUser,authorizeRoles} = require('../middleware/auth');
router.route("/register").post(registerUser);
router.route("/login").post(loginUser); 
router.route("/logout").get(logout); 
router.route("/me").get(isAuthenticatedUser,getUserDetails);
router.route("/password/update").put(isAuthenticatedUser,updatePassword);
router.route("/me/userupdate").put(isAuthenticatedUser,updateProfile);
router.route("/admin/users/:id").get(isAuthenticatedUser,authorizeRoles("admin"),getAllUser);
router.route("/admin/user/:id").get(isAuthenticatedUser,authorizeRoles("admin"),getSingleUser);
router.route("/admin/user/:id").put(isAuthenticatedUser,authorizeRoles("admin"),updateUserRole);
router.route("/admin/user/:id").delete(isAuthenticatedUser,authorizeRoles("admin"),deleteUser);
module.exports = router;